# Site settings
title: Plain Simple Apps
email: 
description: > # this means to ignore newlines until "baseurl:"
  An open-source software company
copyright: Copyright (C) Plain Simple Apps 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
# Syntax Highlighting for Stefan
hightlighter: rouge
