# Site settings
title: Plain and Simple
email: 
description: We make apps, Plain and Simple
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://plain-simple.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]